runtime: python311

env_variables:
 FLASK_SECRET_KEY: "your-secret-key"
 DB_USER: root
 DB_PASSWORD: your-passwordgit
 DB_NAME: guestdb
 DB_SOCKET_PATH: /cloudsql/your-projecti-id:us-central1:your-instance-name

entrypoint: gunicorn -b :$PORT main:app